[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.openssl", "php83Extensions.mbstring", "php83Extensions.sodium", "nginx", "php83Packages.php-fpm"]

[phases.install]
cmds = ["composer install"]

[phases.build]
cmds = ["chmod -R 777 _test/rootCertificates"]

[start]
cmd = "sed -i \"s/8080/$PORT/g\" nginx.conf && php-fpm -y php-fpm.conf && nginx -c /app/nginx.conf"
